In [1]:
import numpy as np #numpy	1.26.4
import matplotlib.pyplot as plt #matplotlib	3.7.1

rng = np.random.default_rng(51)

Инициализация всех используемых в дальнейшем функций.

In [2]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def simpl_f(x):
  res = np.copy(x)
  res[res >= 0] = 1
  res[res < 0 ] = 0
  return res

def tanh(x):
  return np.tanh(x)


In [3]:
class MLP:
  def __init__(self, architecture):
    self.depth = len(architecture) - 1

    self.activation_fn = simpl_f
    # parameters
    self.W = self._init_weights(architecture)
    # Смещение (или порог активации)
    self.b = self._init_biases(architecture)


    # glorot uniform init
  def _init_weights(self, arch):
    net_in = arch[0]
    net_out = arch[-1]
    limit = np.sqrt(6. / (net_in + net_out))
    return [rng.uniform(-limit, limit + 1e-5, size=(arch[i+1], arch[i])) for i in range(self.depth)]

  def _init_biases(self, arch):
    return [rng.random((arch[i+1],1))*2-1 for i in range(self.depth)]

  def set_weights(self, new_W):
    self.W = new_W

  def set_biases(self, new_b):
    self.b = new_b

  def predict(self, X):
    a = X.reshape(self.W[0].shape[1], -1)
    # compute hidden and output layers
    for i in range(self.depth):
      a = np.matmul(self.W[i], a) + self.b[i]
      # if i != self.depth-1:
      a = self.activation_fn(a)
    return a

# Создание моделей для всех лог функций

In [4]:
bool_in_1 = np.array([[0], [1]])
bool_in_2 = np.array([np.array([[0],[0]]),
                            np.array([[0],[1]]),
                            np.array([[1],[0]]),
                            np.array([[1],[1]])]).T
bool_in_2

array([[[0, 0, 1, 1],
        [0, 1, 0, 1]]])

## Not

In [5]:
net_arch_not = (1, 1)
mlp_not = MLP(net_arch_not)

In [6]:
mlp_not.set_weights([np.array([[-1.5]])])
mlp_not.set_biases([np.array([[1.]])])

In [7]:
mlp_not.predict(bool_in_1)

array([[1., 0.]])

## And

In [8]:
net_arch_and = (2, 1)
mlp_and = MLP(net_arch_and)

In [9]:
mlp_and.set_weights([np.array([[1, 1.]])])
mlp_and.set_biases([np.array([[-1.5]])])

In [10]:
mlp_and.predict(bool_in_2)

array([[0., 0., 0., 1.]])

## Or

In [11]:
net_arch_or = (2, 1)
mlp_or = MLP(net_arch_or)

In [12]:
mlp_or.set_weights([np.array([[1, 1.]])])
mlp_or.set_biases([np.array([[-0.5]])])

In [13]:
mlp_or.predict(bool_in_2)

array([[0., 1., 1., 1.]])

## Xor

установка модели

In [14]:
net_arch_xor = (2, 2, 1)
mlp_xor = MLP(net_arch_xor)

In [15]:
mlp_xor.set_weights([np.array([[1., 1.],[1., 1.]]), np.array( [[-2., 1.]])])
mlp_xor.set_biases([np.array([[-1.5], [-0.5]]), np.array( [[-0.5]])])

In [16]:
print(mlp_xor.W[1].shape)
print(mlp_xor.W)
print(mlp_xor.b[0].shape)
print(mlp_xor.b)

(1, 2)
[array([[1., 1.],
       [1., 1.]]), array([[-2.,  1.]])]
(2, 1)
[array([[-1.5],
       [-0.5]]), array([[-0.5]])]


In [17]:
mlp_xor.predict(bool_in_2)

array([[0., 1., 1., 0.]])